trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    sudo apt-get update && sudo apt-get install terraform -y
    terraform version
  displayName: 'Install Terraform'

- script: |
    ls -a
    terraform init
  displayName: 'Init Terraform'

- script: |
    ls -a
    terraform validate
  displayName: 'Validate Terraform'
