name: Preview frontend E2E tests

on:
  push:

jobs:
  wait-for-deployment:
    runs-on: ubuntu-latest
    outputs:
      vercel_url: ${{steps.vercel.outputs.environment_url}}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - id: vercel
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          echo "$BRANCH_NAME"
          python -m pip install requests
          python main.py
      - name: Echo GITHUB_OUTPUT
        env:
         SELECTED_COLOR: ${{ steps.vercel.outputs.SELECTED_COLOR }}
        run: echo "$SELECTED_COLOR"
      - name: Echo GITHUB_ENV
        run: echo "$GITHUB_ENV"
  use-output:
    runs-on: ubuntu-latest
    needs: wait-for-deployment
    steps:
      - name: Echo GITHUB_OUTPUT
        env:
         SELECTED_COLOR: ${{ needs.wait-for-deployment.outputs.SELECTED_COLOR }}
        run: echo "$SELECTED_COLOR"
